server:
  port: 6002
logging:
  level:
    root: info
    # 可以打印 sql
    # cn.mrcode.cachepdp.eshop.cache: debug
    org.springframework.web: TRACE
#  path: ./
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.173:3306/eshop?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: eshop
    password: eshop
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
  kafka:
    bootstrap-servers: 192.168.99.170:9092,192.168.99.171:9092,192.168.99.172:9092
    consumer:
      group-id: eshop-cache-group

mybatis:
#  type-aliases-package: cn.mrcode.cachepdp.eshop.inventory.model
  mapper-locations: classpath*:mapper/*.xml