server:
  port: 7001
logging:
  level:
    root: info
    # 可以打印 sql
    cn.mrcode.cachepdp.eshop.cache.ha: info
    org.springframework.web: TRACE
#  path: ./
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.99.173:3306/eshop?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: eshop
    password: eshop
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
#  type-aliases-package: cn.mrcode.cachepdp.eshop.cache.ha.model
  mapper-locations: classpath*:mapper/*.xml